In [ ]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))

df = pd.DataFrame(scores,
            columns = ["國文","英文","地理","人文","氣候"],
            index=[f"stu{i}" for i in range(1, 51)]
            )
df["國文"]
df["英文"]
df[["國文","地理"]]  #小心， 這是兩個中括弧
df

       國文  英文   地理   人文   氣候
stu1   63  89   90   54   99
stu2   88  95   72   99   94
stu3   58  61   72   95   76
stu4   86  56   53   68   62
stu5   53  90   70   84   83
stu6   73  56   59   82   55
stu7   56  59   98   75   80
stu8   54  80   72   62   71
stu9   71  62   66   60   55
stu10  92  79   79   91   86
stu11  96  71   92   57   95
stu12  67  94   67   97   53
stu13  83  89   66   58   53
stu14  64  96   91   90   95
stu15  80  84   77   87   52
stu16  86  94   57   76   56
stu17  65  54   64   83   79
stu18  71  84   77   89   83
stu19  76  63   57   75   61
stu20  90  99   94   72   91
stu21  83  84   99  100   56
stu22  54  96   69   65   93
stu23  91  93   50   69   84
stu24  63  63   97   74   84
stu25  68  58   93   51   94
stu26  58  85   94   50   81
stu27  73  84   50   95   70
stu28  58  60   68   88   87
stu29  61  81   57   68   52
stu30  53  94   59   52   89
stu31  91  97   92   57   61
stu32  72  98   62   78   81
stu33  58  97   65   99   66
stu34  54  76   66   64   57
stu35  60  65  100   57   85
stu36  73  57   74   58   83
stu37  85  71   91   91   94
stu38  83  95   85   58   56
stu39  96  72   50   81   64
stu40  68  61   72   89   56
stu41  90  70   61  100   79
stu42  87  92   94   70   92
stu43  93  64   79   56   67
stu44  74  63   93   55   51
stu45  61  97   73   89   97
stu46  54  51   51   87   85
stu47  66  93   71   75   75
stu48  87  59   67   53   70
stu49  60  90   85   52  100
stu50  74  93   95   86   97

In [26]:
df.loc["stu1"]
df.loc[["stu1","stu50"]]   #小心， 這是兩個中括弧

       國文  英文  地理  人文  氣候   總分    平均
stu1   63  89  90  54  99  395  79.0
stu50  74  93  95  86  97  445  89.0

In [24]:
sum = df["國文"] + df["英文"] + df["地理"] + df["人文"] + df["氣候"]
df["總分"] = sum
mean = sum / 5
df["平均"] = mean
df

       國文  英文   地理   人文   氣候   總分    平均
stu1   63  89   90   54   99  395  79.0
stu2   88  95   72   99   94  448  89.6
stu3   58  61   72   95   76  362  72.4
stu4   86  56   53   68   62  325  65.0
stu5   53  90   70   84   83  380  76.0
stu6   73  56   59   82   55  325  65.0
stu7   56  59   98   75   80  368  73.6
stu8   54  80   72   62   71  339  67.8
stu9   71  62   66   60   55  314  62.8
stu10  92  79   79   91   86  427  85.4
stu11  96  71   92   57   95  411  82.2
stu12  67  94   67   97   53  378  75.6
stu13  83  89   66   58   53  349  69.8
stu14  64  96   91   90   95  436  87.2
stu15  80  84   77   87   52  380  76.0
stu16  86  94   57   76   56  369  73.8
stu17  65  54   64   83   79  345  69.0
stu18  71  84   77   89   83  404  80.8
stu19  76  63   57   75   61  332  66.4
stu20  90  99   94   72   91  446  89.2
stu21  83  84   99  100   56  422  84.4
stu22  54  96   69   65   93  377  75.4
stu23  91  93   50   69   84  387  77.4
stu24  63  63   97   74   84  381  76.2
stu25  68  58   93   51   94  364  72.8
stu26  58  85   94   50   81  368  73.6
stu27  73  84   50   95   70  372  74.4
stu28  58  60   68   88   87  361  72.2
stu29  61  81   57   68   52  319  63.8
stu30  53  94   59   52   89  347  69.4
stu31  91  97   92   57   61  398  79.6
stu32  72  98   62   78   81  391  78.2
stu33  58  97   65   99   66  385  77.0
stu34  54  76   66   64   57  317  63.4
stu35  60  65  100   57   85  367  73.4
stu36  73  57   74   58   83  345  69.0
stu37  85  71   91   91   94  432  86.4
stu38  83  95   85   58   56  377  75.4
stu39  96  72   50   81   64  363  72.6
stu40  68  61   72   89   56  346  69.2
stu41  90  70   61  100   79  400  80.0
stu42  87  92   94   70   92  435  87.0
stu43  93  64   79   56   67  359  71.8
stu44  74  63   93   55   51  336  67.2
stu45  61  97   73   89   97  417  83.4
stu46  54  51   51   87   85  328  65.6
stu47  66  93   71   75   75  380  76.0
stu48  87  59   67   53   70  336  67.2
stu49  60  90   85   52  100  387  77.4
stu50  74  93   95   86   97  445  89.0

In [30]:
df.iloc[0]
df.iloc[[0,1]]
df.iloc[:3,:5]

      國文  英文  地理  人文  氣候
stu1  63  89  90  54  99
stu2  88  95  72  99  94
stu3  58  61  72  95  76

In [31]:
df.iloc[-10:,:5]

       國文  英文  地理   人文   氣候
stu41  90  70  61  100   79
stu42  87  92  94   70   92
stu43  93  64  79   56   67
stu44  74  63  93   55   51
stu45  61  97  73   89   97
stu46  54  51  51   87   85
stu47  66  93  71   75   75
stu48  87  59  67   53   70
stu49  60  90  85   52  100
stu50  74  93  95   86   97