https://www.perplexity.ai/search/8906abee-eea5-4924-8e07-f2f2029af740

In [10]:
import numpy as np
import pandas as pd

#建立50位學生5個分數，每個分數的值介於50~100之間的隨機整數
scores = np.random.randint(50, 101 ,size=(50, 5))
score_pd = pd.DataFrame(scores, 
                         columns=['國文','英文','數學','地理','歷史'],
                         index=[f'學生{index}' for index in range(1, 51)])
score_pd

      國文   英文   數學   地理   歷史
學生1   60   61   60   93   66
學生2   93   50   84   74   95
學生3   58   90   88   92   97
學生4   61   88   72   52  100
學生5   72   62   84   61   55
學生6   92   56   79   84   55
學生7   54   56   91   57   71
學生8   51  100  100   74   76
學生9   84   53   62   58   76
學生10  87   61   63   83   68
學生11  87   79   77   80   79
學生12  62   77   62   79   65
學生13  78   69   70   67   51
學生14  97   73   55   90   64
學生15  60  100   96   71   92
學生16  80   74   54   87   50
學生17  76   92   59   70   83
學生18  85  100   55   71   83
學生19  53   71   62  100   87
學生20  58   64   70   67   95
學生21  70   55   86   58   79
學生22  85   90   55   50   93
學生23  91   65   60   75  100
學生24  98   68   87   93   92
學生25  52   84   81   81   80
學生26  56   58   51   94   84
學生27  92   78   77   75   78
學生28  97   86   51   51   82
學生29  66   73   82   84   90
學生30  98   66   53   81   91
學生31  90   86   80   75   56
學生32  72   98   87   99   71
學生33  96   67   66   93   50
學生34  94   74   90   69   53
學生35  90   74   67   50   96
學生36  68   54   55   94   84
學生37  84   83   74   81   58
學生38  80   67   69   89   94
學生39  60   92   51   64   76
學生40  97   73   91   56   75
學生41  94  100   80  100   99
學生42  88   62   88   77   52
學生43  74   76   53   55   51
學生44  75   64   56   82   90
學生45  52   62   82   85   61
學生46  83   94   99  100   92
學生47  68   59   58   76   56
學生48  83   96   51   79   82
學生49  69   92   59   74  100
學生50  92   65   76   89   87

In [11]:
scores = np.random.randint(50, 101 ,size=(50, 5))
score_pd = pd.DataFrame(scores, 
                         columns=['國文','英文','數學','地理','歷史'],
                         index=[f'學生{index}' for index in range(1, 51)])
type(score_pd.index)

pandas.core.indexes.base.Index

In [17]:
scores = np.random.randint(50, 101 ,size=(50, 5))
score_pd = pd.DataFrame(scores, 
                         columns=['國文','英文','數學','地理','歷史'],
                         index=[f'學生{index}' for index in range(1, 51)])
score_pd.columns.name = '科目'
score_pd.index.name = '學號'
score_pd

科目    國文   英文   數學   地理   歷史
學號
學生1   63   58   70   84  100
學生2   76  100   86   99   55
學生3   76   67   90   64   88
學生4   96   62   94   75   56
學生5   64   50   63   56   59
學生6   86   62   82   55   65
學生7   78   75   72   71   97
學生8   81   57   59   85   60
學生9   82   77   78   71   88
學生10  97   57   53   78   68
學生11  75   67   72   94  100
學生12  87   67   92   80   95
學生13  89   58   51   88   63
學生14  70   69   67   75   97
學生15  90   77   90   88   78
學生16  59   73   79   70   79
學生17  52   88   72   91   93
學生18  51   73   64   96   69
學生19  61   77   81   67   90
學生20  51   58   71   52   80
學生21  63   93   98   54   71
學生22  92   71  100   77   55
學生23  63   90   67   71   76
學生24  88   50   79   56   82
學生25  56   70   78   90   92
學生26  61   50   88   69   84
學生27  71   63   88   99   51
學生28  72   72   72   56   54
學生29  59   62   51   79   80
學生30  55   61   69   57   73
學生31  68   64   53   76   93
學生32  85   69   84   64   81
學生33  70   85   50   76   78
學生34  98   67   71   96   96
學生35  83   64   84   56   71
學生36  74   50   83   56   92
學生37  92   51   50   69   99
學生38  82   82   67   92   64
學生39  51   55   84   64   62
學生40  56   58   85   63   52
學生41  83   89   52   81   56
學生42  96   56   84   79   67
學生43  69   66   78   98   74
學生44  91   72   83   87   68
學生45  73   62   72  100   64
學生46  56   86   73   94   91
學生47  64   85   91   52   56
學生48  74   73   97   81   53
學生49  62   73   92   57   99
學生50  70   56   63   71  100

In [ ]:
scores = np.random.randint(50, 101 ,size=(50, 5))
score_pd = pd.DataFrame(scores, 
                         columns=['國文','英文','數學','地理','歷史'],
                         index=[f'學生{index}' for index in range(1, 51)])
score_pd.columns.name = '科目'
score_pd.index.name = '學號'
sum_series = np.sum(score_pd, axis=1)
mean_series = score_pd.mean(axis=1)
score_pd['總分'] = sum_series   #若是沒打這兩行，是不會跑出總分與平均的欄位
score_pd['平均'] = mean_series

In [21]:
score_pd

科目    國文   英文   數學   地理   歷史   總分    平均
學號
學生1   66   50   53   81   71  321  64.2
學生2   98   57   96   82   85  418  83.6
學生3   58   78   93   95   73  397  79.4
學生4   67   73   52   76   79  347  69.4
學生5   89   91  100   51   78  409  81.8
學生6   54   77   95   81   75  382  76.4
學生7   98   93   65   77   94  427  85.4
學生8   89   99   60   98   86  432  86.4
學生9   80   66   62   92   87  387  77.4
學生10  75   77   98   68   92  410  82.0
學生11  61   60   66   94   88  369  73.8
學生12  77   54   82   89   53  355  71.0
學生13  72   55   71   53  100  351  70.2
學生14  77  100   96   84   70  427  85.4
學生15  68   83   65   52   54  322  64.4
學生16  60   80   50   86   64  340  68.0
學生17  75   64   96   89   55  379  75.8
學生18  85   50   66   87   77  365  73.0
學生19  71   81   63   88   61  364  72.8
學生20  95   57   94   89   81  416  83.2
學生21  98   53   85   52   66  354  70.8
學生22  85   77   98   50   67  377  75.4
學生23  95   77   66   88   94  420  84.0
學生24  82  100   61   58   61  362  72.4
學生25  66   86   53   74   55  334  66.8
學生26  73   57   94   77   80  381  76.2
學生27  66   54   57   73   64  314  62.8
學生28  85   86   95   88   82  436  87.2
學生29  54  100   50   67  100  371  74.2
學生30  99   57   93   83   60  392  78.4
學生31  70   74   60   73   79  356  71.2
學生32  71   71  100   90   64  396  79.2
學生33  74   84   82   64   97  401  80.2
學生34  83   78   51   92   55  359  71.8
學生35  62   65   83   55   53  318  63.6
學生36  53   86   61   84   89  373  74.6
學生37  89   55   90   61   70  365  73.0
學生38  50   84   83   66   93  376  75.2
學生39  63   70   93   72   88  386  77.2
學生40  93   97   72   84   65  411  82.2
學生41  61   89   83   65   88  386  77.2
學生42  73   77   74   77   67  368  73.6
學生43  59   51   95   65   60  330  66.0
學生44  81   78   98   99   78  434  86.8
學生45  73   95   74   73   57  372  74.4
學生46  79   75   82   88   98  422  84.4
學生47  50   59   78   53   86  326  65.2
學生48  89   62   73  100   92  416  83.2
學生49  82   56   81   74   97  390  78.0
學生50  65   72   72   65   73  347  69.4

In [22]:
#排序
score_pd.sort_values(by='總分', ascending=False)    #ascending 為True就是由小排到大，若為False則是由大排到小

科目    國文   英文   數學   地理   歷史   總分    平均
學號
學生28  85   86   95   88   82  436  87.2
學生44  81   78   98   99   78  434  86.8
學生8   89   99   60   98   86  432  86.4
學生7   98   93   65   77   94  427  85.4
學生14  77  100   96   84   70  427  85.4
學生46  79   75   82   88   98  422  84.4
學生23  95   77   66   88   94  420  84.0
學生2   98   57   96   82   85  418  83.6
學生48  89   62   73  100   92  416  83.2
學生20  95   57   94   89   81  416  83.2
學生40  93   97   72   84   65  411  82.2
學生10  75   77   98   68   92  410  82.0
學生5   89   91  100   51   78  409  81.8
學生33  74   84   82   64   97  401  80.2
學生3   58   78   93   95   73  397  79.4
學生32  71   71  100   90   64  396  79.2
學生30  99   57   93   83   60  392  78.4
學生49  82   56   81   74   97  390  78.0
學生9   80   66   62   92   87  387  77.4
學生39  63   70   93   72   88  386  77.2
學生41  61   89   83   65   88  386  77.2
學生6   54   77   95   81   75  382  76.4
學生26  73   57   94   77   80  381  76.2
學生17  75   64   96   89   55  379  75.8
學生22  85   77   98   50   67  377  75.4
學生38  50   84   83   66   93  376  75.2
學生36  53   86   61   84   89  373  74.6
學生45  73   95   74   73   57  372  74.4
學生29  54  100   50   67  100  371  74.2
學生11  61   60   66   94   88  369  73.8
學生42  73   77   74   77   67  368  73.6
學生37  89   55   90   61   70  365  73.0
學生18  85   50   66   87   77  365  73.0
學生19  71   81   63   88   61  364  72.8
學生24  82  100   61   58   61  362  72.4
學生34  83   78   51   92   55  359  71.8
學生31  70   74   60   73   79  356  71.2
學生12  77   54   82   89   53  355  71.0
學生21  98   53   85   52   66  354  70.8
學生13  72   55   71   53  100  351  70.2
學生50  65   72   72   65   73  347  69.4
學生4   67   73   52   76   79  347  69.4
學生16  60   80   50   86   64  340  68.0
學生25  66   86   53   74   55  334  66.8
學生43  59   51   95   65   60  330  66.0
學生47  50   59   78   53   86  326  65.2
學生15  68   83   65   52   54  322  64.4
學生1   66   50   53   81   71  321  64.2
學生35  62   65   83   55   53  318  63.6
學生27  66   54   57   73   64  314  62.8

In [24]:
sorted_pd = score_pd.sort_values(by='總分', ascending=False)
sorted_pd['總分']

學號
學生28    436
學生44    434
學生8     432
學生7     427
學生14    427
學生46    422
學生23    420
學生2     418
學生48    416
學生20    416
學生40    411
學生10    410
學生5     409
學生33    401
學生3     397
學生32    396
學生30    392
學生49    390
學生9     387
學生39    386
學生41    386
學生6     382
學生26    381
學生17    379
學生22    377
學生38    376
學生36    373
學生45    372
學生29    371
學生11    369
學生42    368
學生37    365
學生18    365
學生19    364
學生24    362
學生34    359
學生31    356
學生12    355
學生21    354
學生13    351
學生50    347
學生4     347
學生16    340
學生25    334
學生43    330
學生47    326
學生15    322
學生1     321
學生35    318
學生27    314
Name: 總分, dtype: int64

In [25]:
sorted_pd = score_pd.sort_values(by='總分', ascending=False)
sorted_pd['總分'].rank(ascending=False,method='min') #若有同名次，則取最小值

學號
學生28     1.0
學生44     2.0
學生8      3.0
學生7      4.0
學生14     4.0
學生46     6.0
學生23     7.0
學生2      8.0
學生48     9.0
學生20     9.0
學生40    11.0
學生10    12.0
學生5     13.0
學生33    14.0
學生3     15.0
學生32    16.0
學生30    17.0
學生49    18.0
學生9     19.0
學生39    20.0
學生41    20.0
學生6     22.0
學生26    23.0
學生17    24.0
學生22    25.0
學生38    26.0
學生36    27.0
學生45    28.0
學生29    29.0
學生11    30.0
學生42    31.0
學生37    32.0
學生18    32.0
學生19    34.0
學生24    35.0
學生34    36.0
學生31    37.0
學生12    38.0
學生21    39.0
學生13    40.0
學生50    41.0
學生4     41.0
學生16    43.0
學生25    44.0
學生43    45.0
學生47    46.0
學生15    47.0
學生1     48.0
學生35    49.0
學生27    50.0
Name: 總分, dtype: float64

In [27]:
sorted_pd = score_pd.sort_values(by='總分', ascending=False)
rand_series = sorted_pd['總分'].rank(ascending=False,method='min')
sorted_pd['名次'] = rand_series

In [28]:
sorted_pd

科目    國文   英文   數學   地理   歷史   總分    平均    名次
學號
學生28  85   86   95   88   82  436  87.2   1.0
學生44  81   78   98   99   78  434  86.8   2.0
學生8   89   99   60   98   86  432  86.4   3.0
學生7   98   93   65   77   94  427  85.4   4.0
學生14  77  100   96   84   70  427  85.4   4.0
學生46  79   75   82   88   98  422  84.4   6.0
學生23  95   77   66   88   94  420  84.0   7.0
學生2   98   57   96   82   85  418  83.6   8.0
學生48  89   62   73  100   92  416  83.2   9.0
學生20  95   57   94   89   81  416  83.2   9.0
學生40  93   97   72   84   65  411  82.2  11.0
學生10  75   77   98   68   92  410  82.0  12.0
學生5   89   91  100   51   78  409  81.8  13.0
學生33  74   84   82   64   97  401  80.2  14.0
學生3   58   78   93   95   73  397  79.4  15.0
學生32  71   71  100   90   64  396  79.2  16.0
學生30  99   57   93   83   60  392  78.4  17.0
學生49  82   56   81   74   97  390  78.0  18.0
學生9   80   66   62   92   87  387  77.4  19.0
學生39  63   70   93   72   88  386  77.2  20.0
學生41  61   89   83   65   88  386  77.2  20.0
學生6   54   77   95   81   75  382  76.4  22.0
學生26  73   57   94   77   80  381  76.2  23.0
學生17  75   64   96   89   55  379  75.8  24.0
學生22  85   77   98   50   67  377  75.4  25.0
學生38  50   84   83   66   93  376  75.2  26.0
學生36  53   86   61   84   89  373  74.6  27.0
學生45  73   95   74   73   57  372  74.4  28.0
學生29  54  100   50   67  100  371  74.2  29.0
學生11  61   60   66   94   88  369  73.8  30.0
學生42  73   77   74   77   67  368  73.6  31.0
學生37  89   55   90   61   70  365  73.0  32.0
學生18  85   50   66   87   77  365  73.0  32.0
學生19  71   81   63   88   61  364  72.8  34.0
學生24  82  100   61   58   61  362  72.4  35.0
學生34  83   78   51   92   55  359  71.8  36.0
學生31  70   74   60   73   79  356  71.2  37.0
學生12  77   54   82   89   53  355  71.0  38.0
學生21  98   53   85   52   66  354  70.8  39.0
學生13  72   55   71   53  100  351  70.2  40.0
學生50  65   72   72   65   73  347  69.4  41.0
學生4   67   73   52   76   79  347  69.4  41.0
學生16  60   80   50   86   64  340  68.0  43.0
學生25  66   86   53   74   55  334  66.8  44.0
學生43  59   51   95   65   60  330  66.0  45.0
學生47  50   59   78   53   86  326  65.2  46.0
學生15  68   83   65   52   54  322  64.4  47.0
學生1   66   50   53   81   71  321  64.2  48.0
學生35  62   65   83   55   53  318  63.6  49.0
學生27  66   54   57   73   64  314  62.8  50.0